export const provinces = [
  {
    id: 1,
    name: "California",
    unavailable: false,
    cities: [
      { id: 1, name: "Los Angeles", unavailable: false },
      { id: 2, name: "San Francisco", unavailable: false },
      { id: 3, name: "San Diego", unavailable: false },
      { id: 4, name: "San Jose", unavailable: false },
      { id: 5, name: "Sacramento", unavailable: false },
    ],
  },
  {
    id: 2,
    name: "New York",
    unavailable: false,
    cities: [
      { id: 1, name: "New York City", unavailable: false },
      { id: 2, name: "Buffalo", unavailable: false },
      { id: 3, name: "Rochester", unavailable: false },
      { id: 4, name: "Yonkers", unavailable: false },
      { id: 5, name: "Syracuse", unavailable: false },
    ],
  },
  {
    id: 3,
    name: "Texas",
    unavailable: false,
    cities: [
      { id: 1, name: "Houston", unavailable: false },
      { id: 2, name: "San Antonio", unavailable: false },
      { id: 3, name: "Dallas", unavailable: false },
      { id: 4, name: "Austin", unavailable: false },
      { id: 5, name: "Fort Worth", unavailable: false },
    ],
  },
  {
    id: 4,
    name: "Florida",
    unavailable: false,
    cities: [
      { id: 1, name: "Miami", unavailable: false },
      { id: 2, name: "Orlando", unavailable: false },
      { id: 3, name: "Tampa", unavailable: false },
      { id: 4, name: "Jacksonville", unavailable: false },
      { id: 5, name: "St. Petersburg", unavailable: false },
    ],
  },
  {
    id: 5,
    name: "Illinois",
    unavailable: false,
    cities: [
      { id: 1, name: "Chicago", unavailable: false },
      { id: 2, name: "Aurora", unavailable: false },
      { id: 3, name: "Naperville", unavailable: false },
      { id: 4, name: "Joliet", unavailable: false },
      { id: 5, name: "Rockford", unavailable: false },
    ],
  },
  {
    id: 6,
    name: "Lazio",
    unavailable: false,
    cities: [
      { id: 1, name: "Rome", unavailable: false },
      { id: 2, name: "Frosinone", unavailable: false },
      { id: 3, name: "Latina", unavailable: false },
      { id: 4, name: "Rieti", unavailable: false },
      { id: 5, name: "Viterbo", unavailable: false },
    ],
  },
  {
    id: 7,
    name: "Lombardy",
    unavailable: false,
    cities: [
      { id: 1, name: "Milan", unavailable: false },
      { id: 2, name: "Bergamo", unavailable: false },
      { id: 3, name: "Brescia", unavailable: false },
      { id: 4, name: "Monza", unavailable: false },
      { id: 5, name: "Como", unavailable: false },
    ],
  },
  {
    id: 8,
    name: "Tuscany",
    unavailable: false,
    cities: [
      { id: 1, name: "Florence", unavailable: false },
      { id: 2, name: "Pisa", unavailable: false },
      { id: 3, name: "Siena", unavailable: false },
      { id: 4, name: "Lucca", unavailable: false },
      { id: 5, name: "Arezzo", unavailable: false },
    ],
  },
  {
    id: 9,
    name: "Sicily",
    unavailable: false,
    cities: [
      { id: 1, name: "Palermo", unavailable: false },
      { id: 2, name: "Catania", unavailable: false },
      { id: 3, name: "Messina", unavailable: false },
      { id: 4, name: "Syracuse", unavailable: false },
      { id: 5, name: "Trapani", unavailable: false },
    ],
  },
  {
    id: 10,
    name: "Veneto",
    unavailable: false,
    cities: [
      { id: 1, name: "Venice", unavailable: false },
      { id: 2, name: "Verona", unavailable: false },
      { id: 3, name: "Padua", unavailable: false },
      { id: 4, name: "Vicenza", unavailable: false },
      { id: 5, name: "Treviso", unavailable: false },
    ],
  },
];
